name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
        id: java
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Setup Bazelisk
        run: go install github.com/bazelbuild/bazelisk@latest && export PATH=$PATH:$(go env GOPATH)/bin
      - uses: actions/checkout@v2
      - name: Run bazel-diff tests
        run: USE_BAZEL_VERSION=last_downstream_green ~/go/bin/bazelisk test //test/...
